name: Check Expiration
on:
  workflow_dispatch:
  schedule:
    - cron: "00 10 1 * *"
jobs:
  Go-Check-Whois:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
      - name: Run the program
        run: uv run domain-watchdog.py
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          DOMAIN: ${{ secrets.DOMAIN }}
